import { AnchorPartner, CurrencyCode, KYCTierInfo, TransactionRecord } from '../types';

export const SUPPORTED_CURRENCIES: Record<CurrencyCode, { name: string; symbol: string; flag: string; decimals: number }> = {
  XLM: { name: 'Stellar Lumens', symbol: '🥏 XLM', flag: '🌐', decimals: 7 },
  USDC: { name: 'USD Coin (Stellar)', symbol: '$', flag: '🇺🇸', decimals: 2 },
  NGN: { name: 'Nigerian Naira', symbol: '₦', flag: '🇳🇬', decimals: 2 },
  EUR: { name: 'Euro', symbol: '€', flag: '🇪🇺', decimals: 2 },
};

export const ANCHOR_PARTNERS: AnchorPartner[] = [
  {
    id: 'cowrie-ngn',
    name: 'Cowrie Integrated Systems (NGN Anchor)',
    country: 'Nigeria',
    flag: '🇳🇬',
    supportedCurrencies: ['NGN', 'USDC', 'XLM'],
    feePercentage: 0.35,
    avgProcessTime: '3-5 seconds',
    status: 'online',
  },
  {
    id: 'flutterwave-gateway',
    name: 'Flutterwave Fiat Rails',
    country: 'Pan-African',
    flag: '🌍',
    supportedCurrencies: ['NGN', 'USDC', 'EUR'],
    feePercentage: 0.5,
    avgProcessTime: '10-30 seconds',
    status: 'online',
  },
  {
    id: 'circle-usdc',
    name: 'Circle USDC Gateway (SEP-24)',
    country: 'Global',
    flag: '🇺🇸',
    supportedCurrencies: ['USDC', 'EUR'],
    feePercentage: 0.1,
    avgProcessTime: 'Instant',
    status: 'online',
  },
  {
    id: 'sika-ghana',
    name: 'SikaRemit (Mobile Money Anchor)',
    country: 'Ghana',
    flag: '🇬🇭',
    supportedCurrencies: ['USDC', 'XLM'],
    feePercentage: 0.4,
    avgProcessTime: '15 seconds',
    status: 'online',
  }
];

export const KYC_TIERS: KYCTierInfo[] = [
  {
    tier: 1,
    title: 'Tier 1 (Basic Identity)',
    dailyLimitUSD: 1000,
    monthlyLimitUSD: 10000,
    requirements: ['Verified Email & Phone Number', 'BVN / NIN Check'],
    status: 'verified',
  },
  {
    tier: 2,
    title: 'Tier 2 (Enhanced Verification)',
    dailyLimitUSD: 25000,
    monthlyLimitUSD: 150000,
    requirements: ['Government Photo ID Upload', 'Proof of Address'],
    status: 'pending',
  },
  {
    tier: 3,
    title: 'Tier 3 (Enterprise & Institutional)',
    dailyLimitUSD: 250000,
    monthlyLimitUSD: 2000000,
    requirements: ['Corporate Documents', 'Biometric Liveness Verification', 'UBO Declaration'],
    status: 'unverified',
  },
];

export const INITIAL_TRANSACTIONS: TransactionRecord[] = [
  {
    id: 'tx_stx_9841029481',
    type: 'transfer',
    sourceCurrency: 'USDC',
    sourceAmount: 250.00,
    destCurrency: 'NGN',
    destAmount: 380125.00,
    fxRate: 1520.50,
    feeUSD: 0.25,
    recipient: {
      name: 'Amina Bello',
      country: 'Nigeria',
      countryFlag: '🇳🇬',
      payoutMethod: 'bank_account',
      bankName: 'Guaranty Trust Bank (GTB)',
      accountNumber: '0123984712',
    },
    status: 'settled',
    stellarTxHash: 'a4f91b7d832e1291847120bcde78f90123456789abcdef0123456789abcdef12',
    anchorName: 'Cowrie Integrated Systems (NGN Anchor)',
    createdAt: new Date(Date.now() - 1000 * 60 * 35).toISOString(),
    completedAt: new Date(Date.now() - 1000 * 60 * 35 + 3200).toISOString(),
    riskScore: 12,
    riskLevel: 'LOW',
    memo: 'Family Support - Lagos',
  },
  {
    id: 'tx_stx_9841029480',
    type: 'deposit',
    sourceCurrency: 'NGN',
    sourceAmount: 500000.00,
    destCurrency: 'USDC',
    destAmount: 328.83,
    fxRate: 0.000657,
    feeUSD: 0.50,
    recipient: {
      name: 'Self (AfroPay Wallet)',
      country: 'Nigeria',
      countryFlag: '🇳🇬',
      payoutMethod: 'stellar_address',
      stellarAddress: 'GAFRO...PAY77',
    },
    status: 'settled',
    stellarTxHash: '8b7f2a1c902e4561847120bcde78f90123456789abcdef0123456789abcdef88',
    anchorName: 'Flutterwave Fiat Rails',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 4).toISOString(),
    completedAt: new Date(Date.now() - 1000 * 60 * 60 * 4 + 4100).toISOString(),
    riskScore: 8,
    riskLevel: 'LOW',
    memo: 'SEP-24 Bank Transfer Deposit',
  },
  {
    id: 'tx_stx_9841029479',
    type: 'transfer',
    sourceCurrency: 'XLM',
    sourceAmount: 1200.00,
    destCurrency: 'USDC',
    destAmount: 138.00,
    fxRate: 0.115,
    feeUSD: 0.001,
    recipient: {
      name: 'Kofi Mensah',
      country: 'Ghana',
      countryFlag: '🇬🇭',
      payoutMethod: 'mobile_money',
      mobileProvider: 'MTN Mobile Money',
      accountNumber: '+233 24 555 0192',
    },
    status: 'settled',
    stellarTxHash: '3c8d1e2f3a4b5c6d7e8f90123456789abcdef0123456789abcdef0123456789a',
    anchorName: 'SikaRemit (Mobile Money Anchor)',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 28).toISOString(),
    completedAt: new Date(Date.now() - 1000 * 60 * 60 * 28 + 2800).toISOString(),
    riskScore: 18,
    riskLevel: 'LOW',
    memo: 'Cross-border path payment NGN/XLM/USDC',
  }
];
